name: Release ScienceDecrypting

on: [create, workflow_dispatch]

jobs:
  build:
    if: ${{ startsWith(github.ref,'refs/tags/') }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: build artifact
        run: pyinstaller -F -w -n ScienceDecrypting gui.py
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScienceDecrypting.exe
          path: dist/ScienceDecrypting.exe
